nt: 10000
aspect: 2.83
nx: 128
ny: 32
use_lateral_fft: false           # whether to compute FFT along x-direction before the POD (usually x-dir is periodic)
use_svd: false                   # whether to use SVD to compute time coefficients & spatial modes (if false: solve EVP)

fieldnames:  
  - "temp"
  - "velx"
  - "vely"

# whether to subtract linear diffusive profile  1 - z from fields before performing POD
subtract_diffusive_profile: 
    - "temp"


datapath: '/usr/scratch4/flhe4523/nek5000/rbc2d/AL63Ra1e5Pr10_fs/interp_data/'
savepath: '/usr/scratch4/flhe4523/rbc2d/AL63Ra1e5Pr10_fs/pod/'
savename: 'AL63Ra1e5Pr10_fs_pod_nt10000.hdf5'
